const express = require("express");
const router = express.Router();
const Controller = require("./controller");
const OtpController = require("../otp/controller");
const DeviceEventController = require("./deviceEventController");
router.get("/", Controller.getAll);
router.get("/status", Controller.deviceStatus);
router.get("/:id", Controller.getById);
router.post("/register", Controller.register);
router.post("/verify-token", Controller.verifyRegisterToken);
router.post("/add", Controller.add);
router.post("/uninstall", Controller.uninstallDevice);
router.post("/track", Controller.track);
router.post("/:id/policy", Controller.setDevicePolicy);
router.get("/:id/policy", Controller.getDevicePolicy);
router.put("/:id/policy/toggle", Controller.toggleDevicePolicy);
router.post("/:id/test-notification", Controller.sendTestNotification);
router.post("/device-event", DeviceEventController.storeEvent);
router.get("/device-event/latest-screenshot", DeviceEventController.getLatestScreenshot);
router.post("/send-otp", OtpController.sendOtp);
router.post("/verify-otp", OtpController.verifyOtp);

module.exports = router;
